Add v2/search
golang/appengine pull request #297
Opened 2023-02-10 11:09 UTC by Deleplace

Integrating the Search legacy bundled service in the appengine/v2 client.

The source is the same as v1:
```
# Copy the Search source files into v2
cp -R ./appengine/search ./appengine/v2/
cp -R ./appengine/internal/search ./appengine/v2/internal

# Fix import paths
sed -i "" "s/\"google.golang.org\/appengine/\"google.golang.org\/appengine\/v2/" ./appengine/v2/search/search.go
sed -i "" "s/\"google.golang.org\/appengine/\"google.golang.org\/appengine\/v2/" ./appengine/v2/search/search_test.go
sed -i "" "s/\"google.golang.org\/appengine/\"google.golang.org\/appengine\/v2/" ./appengine/v2/internal/search/search.pb.go
```

2023-02-10 11:10 UTC, Deleplace commented
CC @ludoch

2023-02-10 11:37 UTC, ludoch requested changes
Great!  Can you also change the copyright year and license text in missing files( proto for example)?

2023-02-10 13:32 UTC, Deleplace commented
Done

2023-02-10 20:58 UTC, jama22 commented
FWIW, I'd be hesitant to merge this PR in without knowing more about the future of Search API

2023-02-24 21:12 UTC, ludoch commented
Valentin, the plan for adding search has now be approved. we can proceed with this PR.
Thanks for your patience and help there.

2023-02-25 11:41 UTC, Deleplace commented
Awesome, please review and merge

2023-03-15 20:58 UTC, ludoch approved these changes

2023-03-15 22:12 UTC, ludoch commented
Valentin, do you know more about the commits that need to be signed? Is it on your side?

2023-03-16 01:21 UTC, merged