Disable dev_appserver.py usage
golang/appengine pull request #302
Opened 2023-02-28 20:12 UTC by MontyCarter

It seems like github actions switched to python3 because devappserver.py no longer runs, and complains with python2 not found.

https://github.blog/changelog/2020-02-27-github-actions-breaking-change-python-2-being-removed-from-all-virtual-environments/

https://github.com/actions/setup-python/issues/543#issuecomment-1319871808

python2 support will not be added to ubuntu 22.04, it seems.

2023-03-01 18:33 UTC, jinglundong commented
I couldn't tell for sure if we use dev_appserver.py in other places in this repo. From my scan of https://github.com/golang/appengine/search?p=1&q=dev_appserver, this PR is okay. 

I approved the workflow run (because this is your first PR I assume). Let's see if workflows pass this time.

2023-03-01 19:03 UTC, jinglundong commented
Tests failed. @MontyCarter

2023-03-01 19:06 UTC, jinglundong commented
```
=== RUN   TestBasicAPICalls
ERROR: (dev_appserver) python2: command not found
    instance_test.go:24: NewInstance: unable to find admin server URL
--- FAIL: TestBasicAPICalls (1.63s)
=== RUN   TestContext
ERROR: (dev_appserver) python2: command not found
    instance_test.go:75: NewContext: unable to find admin server URL
--- FAIL: TestContext (0.46s)
=== RUN   TestUsers
ERROR: (dev_appserver) python2: command not found
    instance_test.go:88: NewInstance: unable to find admin server URL
--- FAIL: TestUsers (0.47s)
FAIL
coverage: 41.6% of statements
FAIL	google.golang.org/appengine/aetest	2.595s
```

2023-03-15 22:11 UTC, ludoch requested changes
I would rather try to make devappserver work again.

IIUC, the new base image used for tests does not include python2, so we need to install it so it can be used by the devappserver.

2023-03-15 23:46 UTC, ludoch commented
Not needed anymore if we merge https://github.com/golang/appengine/pull/304

2023-03-16 01:01 UTC, closed without merging